# Обработка исключительных ситуаций в списке инициализаций
В принципе, обернуть в try/catch можно любую функцию. Но в случае со списком инициализации это не обязательно, поскольку объект еще не начал жизнь и ничего не утечет(НЕ ОЧЕНЬ ПОНЯТНО, ТО ЕСТЬ ЕСЛИ Я ВЫДЕЛЯЮ ПАМЯТЬ В СПИСКЕ ИНИЦИАЛИЗАЦИИ, ПОКА Я НЕ ДОЙДУ ДО ФИГУРНЫХ СКОБОК, ТО ЕСТЬ НАЧАЛА КОНСТРУКТОРА ОНА НЕ ВЫДЕЛИТСЯ) #do/review 
```cpp
MyClass::MyClass()
try
	: m_data{ new int[42]{ 1, 2, 3 } }, m_subObject{ 42 }
{
	/* ... constructor body ... */
}
catch (const exception& e)
{
	// Cleanup memory.
	delete[] m_data;
	m_data = nullptr;
	cout << format("function-try-block caught: '{}'", e.what()) << endl;
}

int main()
{
	try {
		MyClass m;
	}
	catch (const exception& e) {
		cout << format("main() caught: '{}'", e.what()) << endl;
	}
}
/*
	function-try-block caught: 'Exception by SubObject ctor'
	main() caught: 'Exception by SubObject ctor'
*/
```

Эти конструкции не понадобятся, если использовать вектора вместо C style array