# Типы исключений
Мы можем выбросить любой тип с помощью throw, главное, чтобы был соответствующий блок catch, который обработает исключение этого типа или программа упадет

```cpp
auto readIntegerFile(...)
{
	if(..)
	{
		throw invalid_argument{...};
	}
	else if(..)
	{
		throw runtime_error{...};
	}
	else if(..)
	{
		throw 2;
	}
	else
	{
		throw 
	}
}
try {
	myInts = readIntegerFile(filename);
} catch (int e) {
	cerr << format("Unable to open file {} (Error Code {})", filename, e) << endl;
	return 1;
} catch (const invalid_argument& e)
{

} catch (const runtime_error& e)
{

}
catch (...)//any type exception, удобно если
{
	cout << ..;
}
```

Блок try/catch можно сократить:

```cpp
try {
	myInts = readIntegerFile(filename);
} catch (int e) {
	cerr << format("Unable to open file {} (Error Code {})", filename, e) << endl;
	return 1;
} catch (const exception& e)//exception - базовый класс, invalid_argument и runtime_error наследники который реализуют общий функционал what()
{

}
catch (...)//any type exception, удобно если
{
	cout << ..;
}
```

Исключения стоит ловит по const ref потому что:
1. Нет смысла изменять этот объект
2. Мы можем поймать потомка, который при копировании(в случае передачи по значению) в объект базового типа урежится.

Если мы используем несколько блоков catch, после выполнения одного блока, остальные не проверяются на совпадение, т.о. чем ближе по иерархии к базовому классу объект, тем  ниже он должен находиться, среди блоков catch, базовый класс - exception предпоследним, catch который принимает любой объект - последним:

```plantuml
class exception
class logic_error
class out_of_range
exception <|-- logic_error
logic_error <|-- out_of_range
```

```cpp
try{

}catch (const out_of_range& e)
catch (const logic_error& e)
catch (const exception& e)
catch (...)
```

# Исключения и полиморфизм
```plantuml
class exception
class logic_error
class out_of_range
class runtime_error
exception <|-- logic_error
exception <|-- runtime_error
logic_error <|-- out_of_range
```